export const DEFAULT_ANTIGRAVITY_LS_MODEL = "MODEL_PLACEHOLDER_M132";

export const DEFAULT_ANTIGRAVITY_LS_MODEL_FALLBACKS = [
    "MODEL_PLACEHOLDER_M132",
    "MODEL_PLACEHOLDER_M20",
    "MODEL_PLACEHOLDER_M18",
    "MODEL_PLACEHOLDER_M16",
    "MODEL_PLACEHOLDER_M36",
];
